# Build the Android APK without Gradle:
#   aapt2 link -> javac -> d8 -> put classes.dex into APK -> zipalign -> apksigner
# Three gotchas handled here:
#   1) aapt2 / d8 cannot handle non-ASCII paths -> build in an ASCII-only temp dir, copy back after
#   2) classes generated by javac 21 make build-tools 34 R8/d8 fail -> pin JDK 11..18
#   3) native tools write warnings to stderr -> keep ErrorActionPreference Continue and check LASTEXITCODE
$ErrorActionPreference = 'Continue'
$root    = Split-Path -Parent $MyInvocation.MyCommand.Path
$sdk     = Join-Path $root 'android-sdk'
$bt      = Join-Path $sdk 'build-tools\android-14'
$ajSrc   = Join-Path $sdk 'platform\android-34\android.jar'
$proj    = Join-Path $root 'android'
$release = Join-Path $root 'Release'
$work    = Join-Path $env:SystemDrive 'mazi_apk_build'      # must be ASCII
# APK file name (kept as the Chinese app name; built from code points so this script stays ASCII)
$apkName = [string]([char]0x5199) + [string]([char]0x4F5C) + '.apk'

foreach ($p in @($bt, $ajSrc, $proj)) { if (-not (Test-Path $p)) { throw "Missing build component: $p  -- run first: powershell -ExecutionPolicy Bypass -File .\获取安卓SDK.ps1" } }
if (Test-Path $work) { Remove-Item $work -Recurse -Force }
New-Item -ItemType Directory -Force -Path $work, "$work\gen", "$work\classes", "$work\dex", $release | Out-Null

# 0) sync project into the ASCII work dir (includes the latest web page and android.jar)
Copy-Item "$proj\*" $work -Recurse -Force
New-Item -ItemType Directory -Force -Path "$work\assets" | Out-Null
Copy-Item (Join-Path $root 'index.html') "$work\assets\index.html" -Force
Copy-Item $ajSrc "$work\android.jar" -Force
$aj = "$work\android.jar"
Write-Host "[0/6] project synced to $work"

# 1) compile resources
& "$bt\aapt2.exe" compile --dir "$work\res" -o "$work\res.zip" 2>$null
if ($LASTEXITCODE -ne 0) { throw "aapt2 compile failed" }
Write-Host "[1/6] resources compiled"

# 2) link resources + generate R.java + pack assets
#    target-sdk 35: Android 15 (API 35) refuses to install APKs with targetSdk < 35
& "$bt\aapt2.exe" link -o "$work\base.apk" -I $aj --manifest "$work\AndroidManifest.xml" `
  -R "$work\res.zip" --java "$work\gen" -A "$work\assets" `
  --min-sdk-version 24 --target-sdk-version 35 --version-code 1 --version-name 1.0.0 `
  --auto-add-overlay 2>$null
if ($LASTEXITCODE -ne 0) { throw "aapt2 link failed" }
Write-Host "[2/6] resources linked"

# 3) compile Java (needs JDK 11..18)
$javaHome = $null
foreach ($cand in (Get-ChildItem 'C:\Program Files\Java' -Directory -ErrorAction SilentlyContinue | Sort-Object Name -Descending)) {
  if ($cand.Name -match 'jdk-(\d+)') {
    $major = [int]$Matches[1]
    if ($major -ge 11 -and $major -le 18) { $javaHome = $cand.FullName; break }
  }
}
if (-not $javaHome) {
  $javaHome = (Get-ChildItem 'C:\Program Files\Java' -Directory -ErrorAction SilentlyContinue | Where-Object Name -like 'jdk-*' | Sort-Object Name -Descending | Select-Object -First 1).FullName
  Write-Host "      WARNING: no JDK 11..18 found, falling back to $javaHome (javac 21+ may break d8)"
}
$env:JAVA_HOME = $javaHome
$javac = Join-Path $javaHome 'bin\javac.exe'
$srcs  = @(Get-ChildItem "$work\src" -Recurse -Filter *.java | ForEach-Object FullName)
$srcs += @(Get-ChildItem "$work\gen" -Recurse -Filter *.java | ForEach-Object FullName)
& $javac -nowarn -source 8 -target 8 -bootclasspath $aj -encoding UTF-8 -d "$work\classes" $srcs 2>$null
if ($LASTEXITCODE -ne 0) { throw "javac failed" }
Write-Host "[3/6] Java compiled (javac: $javaHome)"

# 4) d8 -> dex
$classes = @(Get-ChildItem "$work\classes" -Recurse -Filter *.class | ForEach-Object FullName)
& "$bt\d8.bat" --lib $aj --min-api 24 --output "$work\dex" $classes 2>$null
if ($LASTEXITCODE -ne 0) { throw "d8 failed" }
Write-Host "[4/6] dex generated"

# 5) put classes.dex into the APK (keep resources.arsc uncompressed for Android 11+)
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem
$dex = "$work\dex\classes.dex"
if (-not (Test-Path $dex)) { throw "classes.dex missing" }
$zip = [System.IO.Compression.ZipFile]::Open("$work\base.apk", 'Update')
try {
  $arsc = $zip.GetEntry('resources.arsc')
  if ($null -ne $arsc -and $arsc.CompressedLength -ne $arsc.Length) {
    $tmp = "$work\arsc.bin"
    [System.IO.Compression.ZipFileExtensions]::ExtractToFile($arsc, $tmp, $true)
    $arsc.Delete()
    [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $tmp, 'resources.arsc', [System.IO.Compression.CompressionLevel]::NoCompression) | Out-Null
    Remove-Item $tmp -Force
    Write-Host "      resources.arsc stored uncompressed"
  }
  $e = $zip.GetEntry('classes.dex')
  if ($null -ne $e) { $e.Delete() }
  [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $dex, 'classes.dex', [System.IO.Compression.CompressionLevel]::Optimal) | Out-Null
} finally { $zip.Dispose() }
Write-Host "[5/6] classes.dex packed into APK"

# 6) align + sign
& "$bt\zipalign.exe" -f -p 4 "$work\base.apk" "$work\aligned.apk" 2>$null
if ($LASTEXITCODE -ne 0) { throw "zipalign failed" }
$ks = Join-Path $sdk 'debug.keystore'
$keytool = Join-Path $javaHome 'bin\keytool.exe'
# Keep the debug keystore OUTSIDE the scratch dir so the signing key stays stable.
# If the key changes between builds, Android refuses in-place updates
# (INSTALL_FAILED_UPDATE_INCOMPATIBLE) and reinstalling wipes app data.
if (-not (Test-Path $ks)) {
  & $keytool -genkeypair -keystore $ks -storepass android -keypass android -alias androiddebugkey `
      -dname "CN=Android Debug,O=Android,C=CN" -keyalg RSA -keysize 2048 -validity 10000 2>$null | Out-Null
  Write-Host "      created persistent debug keystore: $ks"
}
$outApk = Join-Path $release $apkName
& "$bt\apksigner.bat" sign --ks $ks --ks-pass pass:android --key-pass pass:android `
    --v1-signing-enabled true --v2-signing-enabled true --v3-signing-enabled true --v4-signing-enabled false --out $outApk "$work\aligned.apk" 2>$null
if ($LASTEXITCODE -ne 0) { throw "apksigner failed" }
& "$bt\apksigner.bat" verify --print-certs $outApk 2>$null | Select-Object -First 5
Write-Host "[6/6] signed"
$kb = [math]::Round((Get-Item $outApk).Length / 1KB)
Write-Host ("APK: " + $outApk + "  (" + $kb + " KB)")
